DWP.InspiringDigital/Controllers/ActivityController.cs
using DWP.InspiringDigital.Dal;
using DWP.InspiringDigital.Models;
using DWP.InspiringDigital.Models.ViewModels;
using DWP.InspiringDigital.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DWP.InspiringDigital.Controllers
{
    public class ActivityController : Controller
    {
        private readonly IGenricRepository<ProgressRecord> _progressRecordRepository;
        private readonly IUserProfileService _userProfileService;
        private readonly IActivityService _activityService;

        public ActivityController(IActivityService activityService, IUserProfileService userProfileService, IGenricRepository<ProgressRecord> progressRecordRepository)
        {
            _activityService = activityService;
            _userProfileService = userProfileService;
            _progressRecordRepository = progressRecordRepository;
        }

        public ActionResult Index()
        {
            var activities = _activityService.GetActivities();
            var activitiesViewModel = new ActivitiesViewModel
            {
                GettingStartedActivities = activities.Where(x => x.Type == Models.ActivityType.GettingStarted).Select(x => new ActivityViewModel(x, _userProfileService.GetActivityComplete(x), _userProfileService.GetActivityChosen(x))).ToList(),
                JobHuntingActivities = activities.Where(x => x.Type == Models.ActivityType.JobHunting).Select(x => new ActivityViewModel(x, _userProfileService.GetActivityComplete(x), _userProfileService.GetActivityChosen(x))).ToList()
            };

            return View(activitiesViewModel);
        }

        public ActionResult GetStarted(int[] Chosen)
        {
            var progressRecords = _userProfileService.GetCurrentProfile().ProgressRecords;
            foreach (var progressRecord in progressRecords)
            {
                progressRecord.IsChosen = Chosen == null ? false : Chosen.Contains(progressRecord.ActivityId);
                _progressRecordRepository.Update(progressRecord);
            }


            var activities = _activityService.GetActivities();
            var activitiesViewModel = new ActivitiesViewModel
            {
                GettingStartedActivities = activities.Where(x => x.Type == Models.ActivityType.GettingStarted).Select(x => new ActivityViewModel(x, _userProfileService.GetActivityComplete(x), _userProfileService.GetActivityChosen(x))).ToList(),
                JobHuntingActivities = activities.Where(x => x.Type == Models.ActivityType.JobHunting).Select(x => new ActivityViewModel(x, _userProfileService.GetActivityComplete(x), _userProfileService.GetActivityChosen(x))).ToList()
            };

            return RedirectToAction("NextChosenActivity");
        }

        public ActionResult Repeat(int id)
        {
            var activity = _activityService.GetActivity(id);
            _userProfileService.SetActivityComplete(activity, false);
            _userProfileService.UpdateProgressForActivity(activity, 1);

            return RedirectToAction("Index", activity.Controller);
        }

        public ActionResult NextChosenActivity()
        {
            var chosenProgressRecord = _userProfileService.GetCurrentProfile().ProgressRecords.FirstOrDefault(x => x.IsChosen && !x.IsComplete);
            if (chosenProgressRecord == null)
                return RedirectToAction("Index");

            return RedirectToAction("Index", chosenProgressRecord.Activity.Controller);
        }
    }
}

DWP.InspiringDigital/Views/Browser/Browser1.cshtml
@{
    Layout = "~/Views/Shared/_Activity.cshtml";
}

<h2>The web browser</h2>

<p>A web browser lets you visit websites on the internet.</p>

<p>There are different brands of browser, like Internet Explorer, Safari, Firefox and Chrome. As you get more confident, you will find your favourite. Until then, it doesn’t matter which one you use.</p>

<img class="spaced center" src="~/Images/browsers.png" />

<p>All web browsers have things in common, one of which is the address bar. This is the box in the top of this browser which is currently showing:</p>

<div class="address">http://www.inspiringwork.org/browser/01</div>

<p>This is a ‘web address’ and it tells the web browser what you want to look at on the internet.</p>

<p>When you see a web address, maybe on TV or in a leaflet, you can type it into your web browser’s address bar to visit the website.</p>

<div class="action">
    <div class="action-indicator"><span class="icon-dot"></span>&nbsp;&nbsp;Action</div>
    <p>Type the web address below into your web browser’s address bar at the top. This will take you to the next step in the course.</p>
    <h1>www.inspiringdigital.org/nextstep</h1>
</div>

@section aside {
        
    <a class="icon-help2 help-link"></a>
   
}

DWP.InspiringDigital/Views/Browser/Browser2.cshtml
@{
    Layout = "~/Views/Shared/_Activity.cshtml";

}
<div id="part-one" class="">
    <h2>Viewing multiple websites</h2>

    <p>You can visit more than one website at once in your web browser by opening a new tab.</p>

    <p>
        Look at the top of this page - you should see ‘This is a tab’.<br />
        That’s what a tab looks like in your browser.
    </p>

    <img class="topspaced3" src="~/Images/newtab.png" />

    <div class="hint spaced3 text-center">
        <h2>
            <span style="position: relative; top: -15px;" class="icon-righttoup"></span>
            Your tab will look similar to this
        </h2>
    </div>

    <div class="action">
        <div class="action-indicator"><span class="icon-dot"></span>&nbsp;&nbsp;Action</div>
        <p>Take a note of the web address below:</p>
        <h1>www.inspiringdigital.org/newtab</h1>

        <p>Look for the ‘This is a tab’ tab above. Next to it you will see a small blank tab or a + sign.</p>

        <p>When you tap this, it will open a new tab – then put the web address you noted, into the blank address bar of your new tab.</p>

        <p>Once you’ve done this you’ll see a congratulations message.</p>
    </div>
</div>

<div id="part-two" class="hidden">
    <h2>Welcome back to this tab</h2>

    <p>So now you can go directly to a website using the browser’s address bar and open multiple websites at once using tabs.</p>

    <p>You’ve probably heard people talk about ‘searching the internet’ – this is where you don’t know a specific web address but just know you want to search for something.</p>

    <p>Let’s look at this next, click the button below.</p>

    @Html.ActionLink("Next: Start searching the internet", "StepComplete", new { id = 2 }, new { @class = "btn btn-info btn-lg topspaced2 width75" })
</div>



@section scripts {
    <!--Script references. -->
    <!--The jQuery library is required and is referenced by default in _Layout.cshtml. -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.1.1.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="~/signalr/hubs"></script>
    <!--SignalR script to update the chat page and send messages.-->
    <script>
            // Reference the auto-generated proxy for the hub.
            var chat = $.connection.activityHub;
            // Create a function that the hub can call back to display messages.
            chat.client.showPartTwo = function () {
                // Add the message to the page.
                
                $('#part-one').addClass('hidden');
                $('#part-two').removeClass('hidden');
            };
            // Start the connection.
            $.connection.hub.start().done(function () {
                    chat.server.setClientId();
                    // Clear text box and reset focus for next comment.

            });
    </script>
}

DWP.InspiringDigital/Views/Browser/Browser3.cshtml
@{
    Layout = "~/Views/Shared/_Activity.cshtml";
}


<h2>Searching the internet</h2>

<p>You may have heard of search engines such as Google, Yahoo or Bing! Many browsers even show a search engine first when you open them.</p>

<p>Their job is to help you find websites. You start by putting something you want to search for into their search bar and they give you a list of relevant websites.</p>

<p>For example, if you wanted to find a shop that sold scuba diving equipment nearby, you could type in “scuba diving equipment in Cornwall”.</p>


<div class="action clearfix">
    <div class="hint" style="position: absolute; right: -200px; top: 70px;">
        <span style="position: relative; top: 30px; left: -60px;" class="icon-righttoleft"></span>
        <h1>Use a new tab<br />otherwise you’ll<br />lose this page</h1>
    </div>

    <div class="action-indicator"><span class="icon-dot"></span>&nbsp;&nbsp;Action</div>
    <p>Your mission is to combine what you’ve learnt so far to find a particular book online.</p>

    <p>
        Open a new browser tab<br />
        Type <a class="hint" href="#">www.google.com</a> into the address bar
    </p>

    <p>
        Then use the Google search engine to find a paperback book called<br />
        “The Little Book of Calm” on the Amazon website.
    </p>

    <p>Once you have found it, come back to this tab and type the price into the box below and tap enter.</p>

    <form>
        <div class="col-xs-4">
            <input id="price" type="text" class="form-control" />
        </div>
        <div class="col-xs-4">
            <button id="submit" type="submit" class="btn btn-info btn-lg btn-block">Submit</button>
        </div>
    </form>
</div>


<div class="modal fade" id="correct-modal">
    <div class="modal-dialog">
        <div class="modal-content" style="text-align: center;">
            <div class="modal-header">
                <h2>Good Searching</h2>
            </div>
            <div class="modal-body">
                <p>You’ve been successful in searching the internet.</p>
                <p>Often you will experience boxes like this appearing on a website you’re viewing. These are used to get your attention and can be alert boxes or often used for advertisments.</p>
                <p>Tap the button below to move to the next step.</p>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Next step: Internet Cookies", "StepComplete", new { id = 3 }, new { @class = "btn btn-block btn-info btn-lg topspaced3" })
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<div class="modal fade" id="incorrect-modal">
    <div class="modal-dialog">
        <div class="modal-content" style="text-align: center;">
            <div class="modal-header">
                <h2>Hmm, that doesn’t seem right</h2>
            </div>
            <div class="modal-body">
                <p>That price doesn’t seem right for ‘The Little Book of Calm’.</p>

                Try the following steps:
                <ol>
                    <li>Open a new tab in your internet browser</li>
                    <li>Enter www.google.com in the address bar</li>
                    <li>In the Google search area, type “amazon little book of calm”</li>
                    <li>In the list that appears, click on the first link that says it is the Little Book of Calm on the Amazon website</li>
                </ol>
                <p>Once you have the price, close this alert box and re-enter the price</p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-block btn-info btn-lg topspaced3" data-toggle="modal" data-target="#incorrect-modal">Close this alert box</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

@section scripts {
<script>
    $('form').submit(function (event) {
        event.preventDefault();

        var price = $('#price').val();
        if (price.toString() != '£3.99' && price.toString() != '3.99') {

            $('#incorrect-modal').modal('show');
        }
        else {

            $('#correct-modal').modal('show');
        }
    });

</script>

}

DWP.InspiringDigital/Views/Browser/Browser4.cshtml
@{
    Layout = "~/Views/Shared/_Activity.cshtml";
}


<h2>Time for a cookie</h2>

<p>You might find that lots of websites ask your permission to use cookies.</p>

<p>Their job is to help you find websites. You start by putting something you want to search for into their search bar and they give you a list of relevant websites.Cookies are generally seen as a positive thing and let websites personalise their content and improve their service for you.</p>

<p>Some cookies collect data across many websites so they can show you relevant adverts or news – in the same way that supermarkets collect information on ‘club cards’ about what you buy regularly to give you money off vouchers.</p>

<p>Since 2012 it is required that websites ask your consent to use cookies. It is your choice not to accept cookies, but often you will not be able to use the website if you do not.</p>

<div class="action clearfix">
    <div class="action-indicator"><span class="icon-dot"></span>&nbsp;&nbsp;Action</div>
    <p>You’ll see at the bottom of your screen, the Inspiring Digital cookie statement has appeared.</p>

    <p>Click on ‘I accept’ next to the statement to move onto the final step of your course.</p>

</div>

<p>Find out more information on cookies and how to manage them at <a class="hint" href="www.cookiepedia.co.uk">www.cookiepedia.co.uk</a></p>


@section Footer {
    <div class="footer-bar topspaced4">
        <div class="container">
            <div class="body-content">
                <div class="hint">
                    <span class="hint icon-downtoup" style="position:absolute; top: -50px; left: -25px; font-size: 60px;"></span>
                    <h2>What’s this doing down here? Read the main page first</h2>
                </div>

                <div class="row">
                    <p class="col-xs-9">We use cookies to ensure that we give you the best experience on our website. If you continue we'll assume that you are happy to receive cookies on this website.</p>
                    <div class="col-xs-3">
                        @Html.ActionLink("I accept", "StepComplete", new { id = 4 }, new { @class = "btn btn-warning btn-block btn-lg" })
                    </div>
                </div>


            </div>
        </div>
    </div>
}

DWP.InspiringDigital/Views/Browser/Browser5.cshtml
@{
    Layout = "~/Views/Shared/_Activity.cshtml";
}


<h2>Registering with websites</h2>

<h2 class="hint spaced3">This is the last step before you’ve completed this topic</h2>

<p>Lots of websites will ask you to register with them in order to use their service. This may be to let the website remember your details, be able to deliver your purchases or to let you log-in again at a later time.</p>Lots of websites will ask you to register with them in order to use their service. This may be to let the website remember your details, be able to deliver your purchases or to let you log-in again at a later time.

<p>While each website will ask you to register in slightly different ways, they do have many similarities like asking your email and creating a memorable password.</p>



<div class="action clearfix">
    <div class="action-indicator"><span class="icon-dot"></span>&nbsp;&nbsp;Action</div>
    <p>The next page shows a typical registration form.</p>

    <p>Fill in the details and read the help guides at the side. By doing this you will register with Inspiring Digital and save your progress so far, as well as becoming familiar with the registration process.</p>
</div>


@Html.ActionLink("Go to the registration form", "Register", new { }, new { @class = "btn btn-info btn-lg btn-block", @id = "register-button" })

<div class="modal fade" id="register-modal">
    <div class="modal-dialog">
        <div class="modal-content" style="text-align: center;">
            <div class="modal-header">
                <h2>You're already registered</h2>
            </div>
            <div class="modal-body">
                <p>You've already filled in the registration form once, so lets skip straight to the summary.</p>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Skip to summary", "Summary", new {}, new { @class = "btn btn-block btn-info btn-lg topspaced3" })
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

@if (Request.IsAuthenticated)
{ 
    @section scripts {
        <script>
            $('#register-button').click(function (event) {
                event.preventDefault();
                $('#register-modal').modal('show');
            });
        </script>
    }
}

DWP.InspiringDigital/Views/Browser/NewTab.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="body-content center">
        <a href="#" class="pre-header">SUCCESS</a>
        <h1>So you got the new tab sorted</h1>
        <p>
            You’re able to open as many tabs as you want. It’s really useful if you want to compare products or services on different websites as you can click on the tabs at the top of your browser to move back and forth between websites.
        </p>
        <p>
            Once you’re finished with a tab, close it down by clicking on the small cross in the tab.
        </p>
    </div>
    <div class="body-content">

        <div class="action">
            <div class="action-indicator"><span class="icon-dot"></span>&nbsp;&nbsp;Action</div>
            &nbsp;&nbsp;
            Close this tab now
        </div>
    </div>
</div>


@section scripts {
    <!--Script references. -->
    <!--The jQuery library is required and is referenced by default in _Layout.cshtml. -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.1.1.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="~/signalr/hubs"></script>
    <!--SignalR script to update the chat page and send messages.-->
    <script>
        // Reference the auto-generated proxy for the hub.
        var chat = $.connection.activityHub;
        // Create a function that the hub can call back to display messages.
        chat.client.hello = function () {
            // Add the message to the page.
            alert('newtab');
        };
        // Start the connection.
        $.connection.hub.start().done(function () {
        //    chat.server.updatePreviousTab();
            
            window.onbeforeunload = function (e) {
                chat.server.updatePreviousTab();
            };

        });
    </script>
}

DWP.InspiringDigital/Views/Browser/Register.cshtml
@model DWP.InspiringDigital.Models.RegisterModel
@{
    Layout = "~/Views/Shared/_Activity.cshtml";
}


<h2>Registration form</h2>


@using (Html.BeginForm("Register", "Browser", new { id = 3 }, FormMethod.Post, new { @class = "topspaced4" }))
   {
    <div class="form-group">
        @Html.LabelFor(m => m.FirstName)
        @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control", data_hint_text = "#hintFirstName" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.LastName)
        @Html.TextBoxFor(m => m.LastName, new { @class = "form-control", data_hint_text = "" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.UserName)
        @Html.TextBoxFor(m => m.UserName, new { @class = "form-control", data_hint_text = "#hintEmail" })
    </div>
    <div class="checkbox">        
        <label>
            @Html.CheckBoxFor(m => m.NoEmail)If you don't have an email address yet, tap this box
        </label>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Password)
        @Html.PasswordFor(m => m.Password, new { @class = "form-control", data_hint_text = "#hintPassword" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ConfirmPassword)
        @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control", data_hint_text = "#hintConfirmPassword" })
    </div>

    <button type="submit" class="btn btn-info btn-block btn-lg">All done, tap here to finish</button>
   }

@section aside {

<div id="hintFirstName" class="hint register-hint hidden" style="position: absolute; left: 20px; top: 96px;">
    <span style="position: relative; top: 30px; left: -44px; font-size: 14px;" class="icon-righttoleft"></span>
    <h2>Sometimes websites will ask for your first name and last name separately.</h2>
    <h2 class="topspaced4">Often this is so they can personalise the website later on with your name, such as “Hello Bernard”.</h2>
</div>

<div id="hintEmail" class="hint register-hint hidden" style="position: absolute; left: 20px; top: 284px;">
    <span style="position: relative; top: 30px; left: -44px; font-size: 14px;" class="icon-righttoleft"></span>
    <h2>Websites will always ask you for your email address when registering.</h2>
    <h2 class="topspaced4">This is so you can log-in to the website again at a later date – using your email address to identify yourself.</h2>
</div>

<div id="hintPassword" class="hint register-hint hidden" style="position: absolute; left: 20px; top: 254px;">
    <span style="position: relative; top: 186px; left: -46px; font-size: 14px;" class="icon-righttoleft"></span>
    <h2>Passwords are used to keep your log-in secure – only you should ever know your password.</h2>
    <h2 class="topspaced4">A good tip is to use a phrase rather than just a single word. For example ‘this is fun’</h2>
    <h2 class="topspaced4">Tap here to read some tips about creating and remembering passwords.</h2>
</div>

<div id="hintConfirmPassword" class="hint register-hint hidden" style="position: absolute; left: 20px; top: 254px;">
    <span style="position: relative; top: 276px; left: -46px; font-size: 14px;" class="icon-righttoleft"></span>
    <h2>Forms often don’t show the letters as you type, but small circles in place of the letters.</h2>
    <h2 class="topspaced4">This is to stop someone who may be looking at your screen seeing your password.</h2>
    <h2 class="topspaced4">It also means you could mistype your password. Which is why most websites ask you to enter it twice.</h2>
</div>

}

DWP.InspiringDigital/Views/Browser/Registered.cshtml
@{
    Layout = "~/Views/Shared/_Activity.cshtml";
}

<h2>Thanks for registering</h2>

<p>Registration forms generally increase in complexity with the level of security needed. For example, financial service providers will ask for more details and have several layers of verification to protect your account.</p>

<p>Once registered, many websites ask you to confirm your identity, often with one of the following methods:</p>

<ul>
    <li>
        Sending you an email containing a button or link you click as
        confirmation
    </li>
    <li>
        Asking for a mobile phone number to send a confirmation code via SMS
    </li>
    <li>
        Phoning your mobile number with a recorded confirmation message
    </li>
</ul>

<p>We haven’t done this as part of your course.</p>

@Html.ActionLink("Next: Summary", "Summary", new { }, new { @class = "btn btn-info btn-lg topspaced2 width75" })

DWP.InspiringDigital/Views/Browser/Summary.cshtml
@{
    Layout = "~/Views/Shared/_Activity.cshtml";
}

<h2>Congratulations!</h2>


<p>You’ve gone through all the steps and should now be familiar with:</p>


<ul>
    <li>
        Using your web browser’s address bar to visit websites
    </li>
    <li>
        Looking at multiple websites using tabs in your web browser
    </li>
    <li>
        Opening and closing browser tabs
    </li>
    <li>
        Searching the internet using a search engine
    </li>
    <li>
        Understanding pop-up windows
    </li>
    <li>
        Understanding internet cookies and accepting cookie policies
    </li>
    <li>
        Registering with a website
    </li>
    <li>
        Creating secure passwords
    </li>
</ul>

<p>You can go over any of the above again at any time by choosing to repeat the topic from your dashboard.</p>

<h3>What to do now</h3>

<p>You can now either move straight on to your next topic or return to the dashboard to review your progress.</p>

@Html.ActionLink("Next topic: Starting to use email", "NextChosenActivity", "Activity", new { }, new { @class = "btn btn-info btn-lg btn-block" })

@Html.ActionLink("Return to the dashboard", "Index", "Activity", new { }, new { @class = "btn btn-info-inverse btn-lg btn-block" })